version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1

jobs:
  rspec:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: gem install sinatra
      - run: gem install rack-test
      - run: gem install json-schema
      - run: gem install rspec
      - run: rspec
  rubocop:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: gem install rubocop
      - run: rubocop
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - heroku/deploy-via-git

workflows:
  version: 2
  pipeline:
    jobs:
      - rspec
      - rubocop:
          requires:
            - rspec
      - deploy:
          requires:
            - rubocop
