version: 2
jobs:
  rspec:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: gem install sinatra
      - run: gem install rack-test
      - run: gem install json-schema
      - run: gem install rspec
      - run: rspec
  rubocop:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: gem install rubocop
      - run: rubocop
workflows:
  version: 2
  pipeline:
    jobs:
      - rspec
      - rubocop:
          requires:
            - rspec
